### ISSUE TITLE
Add width calculation

### ISSUE THREAD

**Issue by arkitrave** [mwunsch/jquery-renewal#1]
CSS should not be left in the position of having to set width: 80000em for the carousel to work. Automatic width calculation will allow for variable width carousels where the width cannot possibly be known in the stylesheet.

**Comment by mwunsch** [comment]
Width _is_ calculated: 

``` javascript
    element.css({
      'position': 'relative',
      'width': getItemWidth(),
      'left': -getItemWidth(conf.start)
    });
```
